/**
 * Pseudo-noise (PN) sequence generation for the DSSS spread-spectrum codec.
 *
 * We use Maximum-length sequences (M-sequences) generated by a Linear Feedback
 * Shift Register (LFSR). M-sequences have ideal autocorrelation properties:
 * the in-phase autocorrelation is the sequence length L, while every other
 * shift gives -1. This makes correlation-based despreading robust against the
 * music's own spectral content, which appears as roughly white noise relative
 * to the deterministic PN.
 *
 * The chosen primitive polynomial determines the LFSR taps. We provide
 * pre-validated taps for orders 7-16 (sequence lengths 127 - 65535).
 *
 * Reference: Proakis, Digital Communications (4th ed.), §13.2.2.
 */

/**
 * Galois-LFSR XOR masks for primitive polynomials of orders 7-16. Each mask
 * represents the polynomial minus its highest-degree term, shifted so that
 * after a right-shift by 1, XORing the state with the mask injects the
 * feedback at the right positions.
 *
 * Right-shift Galois LFSR:
 *   lsb = state & 1
 *   state = state >>> 1
 *   if (lsb) state ^= mask
 *
 * Derived from Wikipedia's "Linear-feedback shift register" article and
 * verified to produce maximum-length sequences (period 2^order - 1).
 */
const GALOIS_MASKS: Record<number, number> = {
  7: 0x60,    // x^7 + x^6 + 1
  8: 0xB8,    // x^8 + x^6 + x^5 + x^4 + 1
  9: 0x110,   // x^9 + x^5 + 1
  10: 0x240,  // x^10 + x^7 + 1
  11: 0x500,  // x^11 + x^9 + 1
  12: 0xE08,  // x^12 + x^11 + x^10 + x^4 + 1
  13: 0x1C80, // x^13 + x^12 + x^11 + x^8 + 1
  14: 0x3802, // x^14 + x^13 + x^12 + x^2 + 1
  15: 0x6000, // x^15 + x^14 + 1
  16: 0xD008, // x^16 + x^15 + x^13 + x^4 + 1
}

/**
 * Generate an M-sequence of length `length` using a Galois LFSR of order
 * `order` (length must be ≤ 2^order - 1). Output is ±1 values stored as
 * Int8Array.
 *
 * Different seeds produce different cyclic shifts of the same M-sequence; for
 * subcarriers that need different spreading codes, use different seeds.
 */
export function makeMSequence(order: number, seed: number, length: number): Int8Array {
  if (!(order in GALOIS_MASKS)) {
    throw new Error(`pn: no primitive polynomial known for order ${order} (supported: 7-16)`)
  }
  const period = (1 << order) - 1
  if (length > period) {
    throw new Error(`pn: length ${length} exceeds M-sequence period ${period} for order ${order}`)
  }
  if (seed <= 0 || seed >= (1 << order)) {
    throw new Error(`pn: seed must be in [1, 2^${order}-1]`)
  }
  const mask = GALOIS_MASKS[order]
  const out = new Int8Array(length)
  let state = seed >>> 0
  for (let i = 0; i < length; i++) {
    const lsb = state & 1
    out[i] = lsb ? 1 : -1
    state = state >>> 1
    if (lsb) state ^= mask
  }
  return out
}

/**
 * Default PN sequence generator used by the masked codec. Returns one PN code
 * per subcarrier, each of `length` chips, statistically uncorrelated via
 * different LFSR seeds.
 */
export function makeCodebook(
  numSubcarriers: number,
  chipsPerCode: number,
  baseSeed = 0x1a2b,
): Int8Array[] {
  // Choose an LFSR order large enough that the period >> chipsPerCode * numSubcarriers,
  // so distinct seeds give distinct, low-cross-correlation shifts of the same
  // M-sequence (acceptable as a starting point — full Gold codes are an
  // upgrade if cross-correlation becomes a bottleneck).
  const order = Math.min(16, Math.max(11, Math.ceil(Math.log2(chipsPerCode * numSubcarriers * 4))))
  const codes: Int8Array[] = []
  for (let s = 0; s < numSubcarriers; s++) {
    const seed = ((baseSeed * (s + 1)) ^ (s + 1)) & ((1 << order) - 1)
    codes.push(makeMSequence(order, seed === 0 ? 1 : seed, chipsPerCode))
  }
  return codes
}
