import { test, expect } from '@playwright/test'
import { ACOUSTIC_FIXTURE_MESSAGE, ACOUSTIC_FIXTURE_PASSPHRASE } from './global-setup'

/**
 * Layer-3 acoustic proof: real getUserMedia + real AudioWorklet, with Chromium's
 * fake audio capture sourcing a pre-encoded acoustic WAV (built in global-setup).
 *
 * STATUS: skipped pending investigation.
 *
 * Verified working:
 *   - Fixture WAV generated by encode UI (acoustic-carrier mode) — PCM 16-bit mono 44.1kHz
 *   - Chromium accepts `--use-file-for-fake-audio-capture` and pipes the file into getUserMedia
 *   - AudioWorklet receives 1024-sample frames at peak amplitude ~9000 (matches FSK encoder)
 *   - AcousticListener locks the preamble after ~36s of capture
 *
 * Blocker: every preamble lock leads to `Acoustic packet checksum mismatch`. The Chromium
 * audio capture pipeline appears to consistently corrupt enough bits between WAV loop
 * iterations to fail CRC32. Suspected cause: implicit resampling (host 48k → context 44.1k)
 * shifting the 1200/1800 Hz Goertzel bands, or echoCancellation/AGC silently applied to
 * fake capture despite the false constraints. Reproduces deterministically with the
 * existing 9-ratio ±0.4% clock-drift search.
 *
 * Next investigations before re-enabling:
 *   1. Try AudioContext(sampleRate: 48000) + acoustic encoder configured for 48kHz
 *   2. Add `--disable-features=WebRtcAllowInputVolumeAdjustment` and related flags
 *   3. Widen the decoder's clockRatios beyond ±0.4% (Chromium drift may be larger)
 *   4. Replace getUserMedia with a programmatic AudioBufferSourceNode → AudioWorklet
 *      route that still exercises the worklet but avoids the capture pipeline
 *
 * Lower-layer test that DOES work: `npm run test:mic-decode` (synthetic MediaStream).
 * Higher-layer test (physical speaker → real mic) is the user-driven path documented in
 * PHYSICAL_AUDIO_TEST_HANDOVER.md.
 */
test.describe('Microphone decode via Chromium fake audio capture', () => {
  test.skip('reveals message from pre-encoded acoustic WAV piped into getUserMedia', async ({ page }) => {
    const logs: string[] = []
    page.on('console', msg => logs.push(`[${msg.type()}] ${msg.text()}`))
    page.on('pageerror', err => logs.push(`[pageerror] ${err.message}`))

    await page.goto('/', { timeout: 60_000 })
    await expect(page.getByText('Carnation Radio')).toBeVisible({ timeout: 60_000 })

    await page.getByTestId('tab-decode').click()
    await page.getByTestId('decode-method-mic').click()
    await page.getByPlaceholder('Enter passphrase...').fill(ACOUSTIC_FIXTURE_PASSPHRASE)

    await page.getByTestId('btn-start-microphone').click()
    await expect(page.getByTestId('mic-listening-panel')).toBeVisible()

    const decodedMsg = page.getByTestId('decoded-message')
    const decodeError = page.locator('.alert-error')

    try {
      await Promise.race([
        expect(decodedMsg).toBeVisible({ timeout: 90_000 }),
        decodeError.waitFor({ timeout: 90_000 }).then(async () => {
          const text = await decodeError.textContent()
          throw new Error(`Mic decode error: ${text}. Console: ${logs.slice(-50).join(' | ')}`)
        }),
      ])
    } catch (err: any) {
      const statusText = await page.getByTestId('mic-status-text').textContent().catch(() => '<no status>')
      const statusDetail = await page.getByTestId('mic-status-detail').textContent().catch(() => '<no detail>')
      throw new Error(
        `${err?.message || err}\nMic status: ${statusText}\nDetail: ${statusDetail}\nConsole (last 50): ${logs.slice(-50).join(' | ')}`,
      )
    }
    await expect(decodedMsg).toHaveText(ACOUSTIC_FIXTURE_MESSAGE)
  })
})
